# **SQL and JupyterNotebook**

In the previous classes, I wanted you to become familiar with the JupyterNotebook interface, but I really did not go into the weeds of what we are doing and why.

We are simulating a scenario where you are able to access a **database system**. Given that the database for this class is really small (ZAGIMORE, HAFHMORE), using Notebooks and SQLite represents a doable solution.

In a real world scenario, the database will likely be available:

*   On cloud (Google Cloud Platform, AWS Amazon, Microsoft Azure)
*   On premise / physically at your the organization

---


### **Questions for you**

1.   What do you think determines this choice (cloud vs on premise)?  
2.   How does it affect a company?
3.   What are important aspects that you should consider, as a business manager?

In [66]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()
while PROJECT_ROOT != PROJECT_ROOT.parent and not (
    (PROJECT_ROOT / "README.md").exists()
    and (PROJECT_ROOT / "requirements.txt").exists()
):
    PROJECT_ROOT = PROJECT_ROOT.parent

if not (PROJECT_ROOT / "requirements.txt").exists():
    raise FileNotFoundError(
        "Could not find the project root. Start Jupyter from the DataManagement-BusinessIntelligence folder."
    )

## **Before We Start**

### **Deep Dive into JupyterNotebooks**


**What does RunTime, Run all, Insert, Tools and more mean**

Edit > Clear Outputs of All Cells

View > Show Line Numbers

Kernel/Run > *All are important*

---



**Execution**

Order is important. You will see, especially as you get more familiar, how tempting it is to go up and down in a notebook. This can lead to errors. If you run things in order you should be fine.

**Common Mistakes.**
The are two common mistakes, that you would not have by using regular scripting code (no notebooks).

*examples showed in class*

*   Example 1: I create a variable, execute the code, and then delete it. Next time I will run the code, it will not work - error: variable does not exist
*   Example 2: I create a variable in a cell, manipulate it in different ways in other cells, but I do not do things in order - wrong results


---


### **For the assignment before submission make sure to:**


1.   **Kernel > Restart Kernel and Clear Outputs of All Cells**
2.   **Run all cells sequentially**
3.   **If things run as before, you can submit. If not, you might want to check your assignment again.**

In [67]:
# Set-up
db_path = (PROJECT_ROOT / "zagimore.db").resolve().as_posix()
connection_string = f"sqlite:///{db_path}"

%reload_ext sql
%sql $connection_string

### **What If**

What if I am trying to access an organization DB, which is clearly not in our Google Drive. Most likely, you will need to tunnel SSH with the database, wherever that is, and then starting querying it. Long story short, you will connect to wherever the DB is to query it.

# **SQL in JupyterNotebook**

You will always need the command ``%%sql``

at the beginning of your code cell, whenever you run SQL code.

In [68]:
# This is a comment in Python (hashtag in front)

In [69]:
%%sql

-- Comments in SQL (two dashes in front)
-- First example of SQL query
-- We are identifying all tables in the database
SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('vendor',),
 ('category',),
 ('product',),
 ('region',),
 ('store',),
 ('customer',),
 ('salestransaction',),
 ('soldvia',)]

In [5]:
%%sql

SELECT *
FROM soldvia
LIMIT 3;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'T111', 1), ('2X2', 'T222', 1), ('3X3', 'T333', 5)]

## **More about SQL**

Main **categories of SQL commands**


*   Data Definition Language: Modify DB structure (``CREATE``, ``ALTER``, ``DROP``)

*   Data Manipulation Language: Insert, modify, retrieve data (``INSERT INTO``, ``UPDATE``, ``SELECT``, ``DELETE``)

*   Data Control Language: To control access (``GRANT``)


*   Transactional Control Language: To manage database transactions (``ROLLBACK``)


---

**SQL Data Types**


*   `CHAR(n)` fixed length $n$-character string
*   `VARCHAR(n)` variable length string with max size $n$
*   `INT` integer
*   `NUMERIC (x, y)` number with $x$ digits, $y$ of which are after the decimal point
*   `DATE` date value *(year, month, day)*


---

**Syntax Notation**

*   `;` end of the SQL command
*   `Not case sensitive`

# **LET'S START!!** 🎊

## **SELECT FROM**

In [6]:
%%sql

-- Retrieve the entire content of the table PRODUCT

SELECT * FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100, 'PG', 'CP'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP')]

In [7]:
%%sql

-- Retrieve the entire contents of the relation PRODUCT and show the columns in the following order: ProductName, ProductID, VendorID, CategoryID, ProductPrice

SELECT productname, ProductID, VendorID, CategoryID, ProductPrice
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('Zzz Bag', '1X1', 'PG', 'CP', 100),
 ('Easy Boot', '2X2', 'MK', 'FW', 70),
 ('Cosy Sock', '3X3', 'MK', 'FW', 15),
 ('Dura Boot', '4X4', 'PG', 'FW', 90),
 ('Tiny Tent', '5X5', 'MK', 'CP', 150),
 ('Biggy Tent', '6X6', 'MK', 'CP', 250),
 ('Hi-Tec GPS', '7X7', 'OA', 'EL', 300),
 ('Power Pedals', '8X8', 'MK', 'CY', 20),
 ('Trusty Rope', '9X9', 'WL', 'CL', 30),
 ('Comfy Harness', '1X2', 'MK', 'CL', 150),
 ('Sunny Charger', '1X3', 'OA', 'EL', 125),
 ('Safe-T Helmet', '1X4', 'PG', 'CY', 40),
 ('Mmm Stove', '2X1', 'WL', 'CP', 80),
 ('Reflect-o Jacket', '2X3', 'PG', 'CY', 35),
 ('Strongster Carribeaner', '2X4', 'MK', 'CL', 20),
 ('Sleepy Pad', '3X1', 'WL', 'CP', 25),
 ('Bucky Knife', '3X2', 'WL', 'CP', 60),
 ('Treado Tire', '3X4', 'OA', 'CY', 30),
 ('Slicky Tire', '4X1', 'OA', 'CY', 25),
 ('Electra Compass', '4X2', 'MK', 'EL', 45),
 ('Mega Camera', '4X3', 'WL', 'EL', 275),
 ('Simple Sandal', '5X1', 'PG', 'FW', 50),
 ('Action Sandal', '5X2', 'PG', 'FW', 70),
 ('Luxo Tent', '5X3', 'OA', 'CP', 500)]

In [8]:
%%sql

-- For the relation PRODUCT, show the ProductID and ProductPrice
SELECT productid, productprice
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 100),
 ('2X2', 70),
 ('3X3', 15),
 ('4X4', 90),
 ('5X5', 150),
 ('6X6', 250),
 ('7X7', 300),
 ('8X8', 20),
 ('9X9', 30),
 ('1X2', 150),
 ('1X3', 125),
 ('1X4', 40),
 ('2X1', 80),
 ('2X3', 35),
 ('2X4', 20),
 ('3X1', 25),
 ('3X2', 60),
 ('3X4', 30),
 ('4X1', 25),
 ('4X2', 45),
 ('4X3', 275),
 ('5X1', 50),
 ('5X2', 70),
 ('5X3', 500)]

In [9]:
%%sql

-- For the relation PRODUCT, show the columns ProductID and ProductPrice and a column showing ProductPrice increased by 10%
SELECT productid, productprice, productprice*1.1
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 100, 110.00000000000001),
 ('2X2', 70, 77.0),
 ('3X3', 15, 16.5),
 ('4X4', 90, 99.00000000000001),
 ('5X5', 150, 165.0),
 ('6X6', 250, 275.0),
 ('7X7', 300, 330.0),
 ('8X8', 20, 22.0),
 ('9X9', 30, 33.0),
 ('1X2', 150, 165.0),
 ('1X3', 125, 137.5),
 ('1X4', 40, 44.0),
 ('2X1', 80, 88.0),
 ('2X3', 35, 38.5),
 ('2X4', 20, 22.0),
 ('3X1', 25, 27.500000000000004),
 ('3X2', 60, 66.0),
 ('3X4', 30, 33.0),
 ('4X1', 25, 27.500000000000004),
 ('4X2', 45, 49.50000000000001),
 ('4X3', 275, 302.5),
 ('5X1', 50, 55.00000000000001),
 ('5X2', 70, 77.0),
 ('5X3', 500, 550.0)]

## **WHERE**

We might be interested in selecting a specific record, if a condition is satisfied. The ``WHERE`` condition determines which row will be retrieved using the following logical operators.

*   `=` Equal to
*   `<` Less than
*   `>` Greater than
*   `<=` Less than or equal to
*   `>=` Greater than or equal to
*   `!=` Not equal to (or `<>`)

Logical conditions can be combined using `AND` and `OR`

In [10]:
%%sql

-- Retrieve the product ID, product name, vendorID, and product price for each product whose price is above $100
SELECT productid, productname, vendorid, productprice
FROM product
WHERE productprice > 100;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('5X5', 'Tiny Tent', 'MK', 150),
 ('6X6', 'Biggy Tent', 'MK', 250),
 ('7X7', 'Hi-Tec GPS', 'OA', 300),
 ('1X2', 'Comfy Harness', 'MK', 150),
 ('1X3', 'Sunny Charger', 'OA', 125),
 ('4X3', 'Mega Camera', 'WL', 275),
 ('5X3', 'Luxo Tent', 'OA', 500)]

In [11]:
%%sql

-- Retrieve the product ID, product name, vendor ID, and product price for each product in the FW category whose price is equal to or below $110

SELECT productid, productname, vendorid, productprice
FROM product
WHERE productprice <= 110 AND categoryid='FW' ;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('2X2', 'Easy Boot', 'MK', 70),
 ('3X3', 'Cosy Sock', 'MK', 15),
 ('4X4', 'Dura Boot', 'PG', 90),
 ('5X1', 'Simple Sandal', 'PG', 50),
 ('5X2', 'Action Sandal', 'PG', 70)]

In [12]:
%%sql

-- Retrieve the vendorID value for each record in the relation PRODUCT
SELECT vendorid
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('PG',),
 ('MK',),
 ('MK',),
 ('PG',),
 ('MK',),
 ('MK',),
 ('OA',),
 ('MK',),
 ('WL',),
 ('MK',),
 ('OA',),
 ('PG',),
 ('WL',),
 ('PG',),
 ('MK',),
 ('WL',),
 ('WL',),
 ('OA',),
 ('OA',),
 ('MK',),
 ('WL',),
 ('PG',),
 ('PG',),
 ('OA',)]

## **DISTINCT**

Return unique entries, without repetitions

In [13]:
%%sql

-- Show one instance of all the different vendorID values in the relation PRODUCT

SELECT DISTINCT vendorid
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('PG',), ('MK',), ('OA',), ('WL',)]

## **ORDER BY**

We can order the values in a query by one or more columns.

In [14]:
%%sql

SELECT * FROM product LIMIT 5;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100, 'PG', 'CP'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP')]

In [15]:
%%sql

-- Retrieve the productID, product name, categoryID, and product price for each product in the FW product category sorted by the product price

SELECT productid, productname, categoryid, productprice
FROM product
WHERE categoryid='FW'
ORDER BY productprice;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('3X3', 'Cosy Sock', 'FW', 15),
 ('5X1', 'Simple Sandal', 'FW', 50),
 ('2X2', 'Easy Boot', 'FW', 70),
 ('5X2', 'Action Sandal', 'FW', 70),
 ('4X4', 'Dura Boot', 'FW', 90)]

In [16]:
%%sql

--Retrieve the product id, product name, category id, and product price for each product in the FW product category, sorted by product price in descending order
SELECT productid, productname, categoryid, productprice
FROM product
WHERE categoryid='FW'
ORDER BY productprice DESC;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('4X4', 'Dura Boot', 'FW', 90),
 ('2X2', 'Easy Boot', 'FW', 70),
 ('5X2', 'Action Sandal', 'FW', 70),
 ('5X1', 'Simple Sandal', 'FW', 50),
 ('3X3', 'Cosy Sock', 'FW', 15)]

In [17]:
%%sql

-- Retrieve the product ID, product name, category ID, and product price for each product, sorted by category ID and, within the same category ID, by product price
SELECT productid, productname, categoryID, productprice
FROM product
ORDER BY categoryid, productprice;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('2X4', 'Strongster Carribeaner', 'CL', 20),
 ('9X9', 'Trusty Rope', 'CL', 30),
 ('1X2', 'Comfy Harness', 'CL', 150),
 ('3X1', 'Sleepy Pad', 'CP', 25),
 ('3X2', 'Bucky Knife', 'CP', 60),
 ('2X1', 'Mmm Stove', 'CP', 80),
 ('1X1', 'Zzz Bag', 'CP', 100),
 ('5X5', 'Tiny Tent', 'CP', 150),
 ('6X6', 'Biggy Tent', 'CP', 250),
 ('5X3', 'Luxo Tent', 'CP', 500),
 ('8X8', 'Power Pedals', 'CY', 20),
 ('4X1', 'Slicky Tire', 'CY', 25),
 ('3X4', 'Treado Tire', 'CY', 30),
 ('2X3', 'Reflect-o Jacket', 'CY', 35),
 ('1X4', 'Safe-T Helmet', 'CY', 40),
 ('4X2', 'Electra Compass', 'EL', 45),
 ('1X3', 'Sunny Charger', 'EL', 125),
 ('4X3', 'Mega Camera', 'EL', 275),
 ('7X7', 'Hi-Tec GPS', 'EL', 300),
 ('3X3', 'Cosy Sock', 'FW', 15),
 ('5X1', 'Simple Sandal', 'FW', 50),
 ('2X2', 'Easy Boot', 'FW', 70),
 ('5X2', 'Action Sandal', 'FW', 70),
 ('4X4', 'Dura Boot', 'FW', 90)]

## **LIKE**

Used for retrieval of records who values partially match a certain criteria

In [18]:
%%sql

-- Retrieve the record for each product whose product name contains the phrase 'Boot'
SELECT *
FROM product
WHERE productname LIKE '%Boot%';

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('2X2', 'Easy Boot', 70, 'MK', 'FW'), ('4X4', 'Dura Boot', 90, 'PG', 'FW')]

## **Aggregate functions**

For calculating and summarizing values

*   `COUNT`
*   `SUM`
*   `AVG`
*   `MIN`
*   `MAX`

In [19]:
%%sql

-- Retrieve the average price of all products
SELECT AVG(productprice)
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[(106.45833333333333,)]

In [20]:
%%sql

-- Retrieve how many products are offered for sale
SELECT COUNT(*)
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[(24,)]

In [21]:
%%sql

-- Retrieve the number of vendors that supply our products
SELECT COUNT(DISTINCT(vendorid))
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[(4,)]

In [22]:
%%sql

-- Retrieve the number of products, average product price, lowest product price, and highest product price in the CP product category
SELECT COUNT(productid), AVG(productprice), MIN(productprice), MAX(productprice)
FROM product
WHERE categoryID='CP';

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[(7, 166.42857142857142, 25, 500)]

## **GROUP BY**

Enable summarizations across the groups of related data within tables.

In [23]:
%%sql

-- For each vendor, retrieve the vendorID, number of products, supplied by the vendor and average price of the products supplied by the vendor

SELECT *
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100, 'PG', 'CP'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP')]

In [24]:
%%sql

-- For each vendor, retrieve the vendorID, number of products, supplied by the vendor and average price of the products supplied by the vendor

SELECT vendorid, COUNT(*), AVG(productprice)
FROM product
GROUP BY vendorid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('MK', 8, 90.0),
 ('OA', 5, 196.0),
 ('PG', 6, 64.16666666666667),
 ('WL', 5, 94.0)]

Let's analyze a bit closer what this `GROUP BY` do

In [25]:
%%sql

--  Something to be careful about, you end up getting the row for the first item in the group by
select * from product
group by vendorid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('2X2', 'Easy Boot', 70, 'MK', 'FW'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL'),
 ('1X1', 'Zzz Bag', 100, 'PG', 'CP'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL')]

In [26]:
%%sql

-- For each vendor, retrieve the vendor ID and the number of products with a product price of $ 100 or higher supplied by the vendor
SELECT vendorid, productprice
FROM product
WHERE vendorid='PG' AND productprice>=100;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('PG', 100)]

In [27]:
%%sql

-- For each vendor, retrieve the vendor ID and the number of products with a product price of $ 100 or higher supplied by the vendor
SELECT vendorid, COUNT(productprice)
FROM product
WHERE productprice >=100
GROUP BY vendorid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('MK', 3), ('OA', 3), ('PG', 1), ('WL', 1)]

In [28]:
result = %sql select * from product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

In [29]:
import pandas as pd
df= pd.DataFrame(result)

df

   productid             productname  productprice vendorid categoryid
0        1X1                 Zzz Bag           100       PG         CP
1        2X2               Easy Boot            70       MK         FW
2        3X3               Cosy Sock            15       MK         FW
3        4X4               Dura Boot            90       PG         FW
4        5X5               Tiny Tent           150       MK         CP
5        6X6              Biggy Tent           250       MK         CP
6        7X7              Hi-Tec GPS           300       OA         EL
7        8X8            Power Pedals            20       MK         CY
8        9X9             Trusty Rope            30       WL         CL
9        1X2           Comfy Harness           150       MK         CL
10       1X3           Sunny Charger           125       OA         EL
11       1X4           Safe-T Helmet            40       PG         CY
12       2X1               Mmm Stove            80       WL         CP
13       2X3        Reflect-o Jacket            35       PG         CY
14       2X4  Strongster Carribeaner            20       MK         CL
15       3X1              Sleepy Pad            25       WL         CP
16       3X2             Bucky Knife            60       WL         CP
17       3X4             Treado Tire            30       OA         CY
18       4X1             Slicky Tire            25       OA         CY
19       4X2         Electra Compass            45       MK         EL
20       4X3             Mega Camera           275       WL         EL
21       5X1           Simple Sandal            50       PG         FW
22       5X2           Action Sandal            70       PG         FW
23       5X3               Luxo Tent           500       OA         CP

In [30]:
df.to_csv(PROJECT_ROOT / "_file.csv", index=False)

In [31]:
#  result = %sql select * from product;
## always nice to see how easy is the Python integration
df[df.productprice > 100].groupby('vendorid').sum()[['productprice']]

          productprice
vendorid
MK                 550
OA                 925
WL                 275

In [32]:
%%sql

-- Consider the groups of products where each group contains the products that are from the same category supplied by the same vendor. For each such group, retrieve the vendor ID, product category ID, number of products in the group, and average price of the products in the group

SELECT categoryID, vendorid, COUNT(productid), AVG(productprice)
FROM product
GROUP BY vendorid, categoryid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('CL', 'MK', 2, 85.0),
 ('CP', 'MK', 2, 200.0),
 ('CY', 'MK', 1, 20.0),
 ('EL', 'MK', 1, 45.0),
 ('FW', 'MK', 2, 42.5),
 ('CP', 'OA', 1, 500.0),
 ('CY', 'OA', 2, 27.5),
 ('EL', 'OA', 2, 212.5),
 ('CP', 'PG', 1, 100.0),
 ('CY', 'PG', 2, 37.5),
 ('FW', 'PG', 3, 70.0),
 ('CL', 'WL', 1, 30.0),
 ('CP', 'WL', 3, 55.0),
 ('EL', 'WL', 1, 275.0)]

In [33]:
%%sql

-- Consider the groups of products where each group contains the products that are from the same category supplied by the same vendor. For each such group, retrieve the vendor ID, product category ID, number of products in the group, and average price of the products in the group

SELECT categoryID, vendorid, COUNT(productid), AVG(productprice)
FROM product
GROUP BY categoryid, vendorid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('CL', 'MK', 2, 85.0),
 ('CL', 'WL', 1, 30.0),
 ('CP', 'MK', 2, 200.0),
 ('CP', 'OA', 1, 500.0),
 ('CP', 'PG', 1, 100.0),
 ('CP', 'WL', 3, 55.0),
 ('CY', 'MK', 1, 20.0),
 ('CY', 'OA', 2, 27.5),
 ('CY', 'PG', 2, 37.5),
 ('EL', 'MK', 1, 45.0),
 ('EL', 'OA', 2, 212.5),
 ('EL', 'WL', 1, 275.0),
 ('FW', 'MK', 2, 42.5),
 ('FW', 'PG', 3, 70.0)]

In [34]:
%%sql

SELECT *
FROM soldvia
LIMIT 5;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'T111', 1),
 ('2X2', 'T222', 1),
 ('3X3', 'T333', 5),
 ('1X1', 'T333', 1),
 ('4X4', 'T444', 1)]

In [35]:
%%sql

-- For each product, retrieve the productID value and total number of product items sold within all the sales transactions (this table is not the product one)
SELECT productid, SUM(noofitems)
FROM soldvia
GROUP BY productid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 2),
 ('1X2', 8),
 ('1X3', 3),
 ('1X4', 7),
 ('2X1', 6),
 ('2X2', 13),
 ('2X3', 5),
 ('2X4', 12),
 ('3X1', 6),
 ('3X2', 2),
 ('3X3', 12),
 ('3X4', 6),
 ('4X1', 2),
 ('4X2', 4),
 ('4X3', 4),
 ('4X4', 7),
 ('5X1', 2),
 ('5X3', 1),
 ('5X5', 2),
 ('6X6', 2),
 ('7X7', 1),
 ('8X8', 4),
 ('9X9', 5)]

In [36]:
%%sql

SELECT *
FROM soldvia
LIMIT 5;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'T111', 1),
 ('2X2', 'T222', 1),
 ('3X3', 'T333', 5),
 ('1X1', 'T333', 1),
 ('4X4', 'T444', 1)]

In [37]:
%%sql

SELECT *
FROM soldvia
WHERE productid='3X3';

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('3X3', 'T011', 3), ('3X3', 'T333', 5), ('3X3', 'T808', 4)]

In [38]:
%%sql

-- For each product, retrieve the ProductID value and the number of sales transactions in which the product was sold

SELECT productid, COUNT(tid)
FROM soldvia
GROUP BY productid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 2),
 ('1X2', 2),
 ('1X3', 2),
 ('1X4', 3),
 ('2X1', 2),
 ('2X2', 6),
 ('2X3', 2),
 ('2X4', 3),
 ('3X1', 2),
 ('3X2', 2),
 ('3X3', 3),
 ('3X4', 2),
 ('4X1', 1),
 ('4X2', 2),
 ('4X3', 2),
 ('4X4', 3),
 ('5X1', 1),
 ('5X3', 1),
 ('5X5', 1),
 ('6X6', 2),
 ('7X7', 1),
 ('8X8', 2),
 ('9X9', 3)]

## **HAVING**

Enable summarizations across the groups of related data within tablesd

Determines which groups will be displayed in the result of a query and, consequently, which groups will not be displayed in the results of a query

A query that contains a `HAVING` clause must also contain a `GROUP BY` clause.

In [39]:
%%sql

-- Consider the groups of products where each group contains the products that are from the same category and supplied by the same vendor. For each such group that has more than one product, retrieve the vendorid, product category id, number of product in the group, and average price of the product in the group

SELECT vendorid, categoryid, COUNT(*), AVG(productprice)
FROM product
GROUP BY categoryid, vendorid
HAVING COUNT(*) > 1;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('MK', 'CL', 2, 85.0),
 ('MK', 'CP', 2, 200.0),
 ('WL', 'CP', 3, 55.0),
 ('OA', 'CY', 2, 27.5),
 ('PG', 'CY', 2, 37.5),
 ('OA', 'EL', 2, 212.5),
 ('MK', 'FW', 2, 42.5),
 ('PG', 'FW', 3, 70.0)]

In [40]:
%%sql


-- Consider the groups of product where each group contains the products that are from the same category, supplied by the same vendor, and whose product price is $ 50 or higher. For each such group that has more than one product, retrieve the vendor id, product category id, number of products in the group, and average price per product.

SELECT vendorid, categoryid, COUNT(*), AVG(productprice)
FROM product
WHERE productprice >= 50
GROUP BY categoryid, vendorid
HAVING COUNT(*) > 1;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('MK', 'CP', 2, 200.0),
 ('WL', 'CP', 2, 70.0),
 ('OA', 'EL', 2, 212.5),
 ('PG', 'FW', 3, 70.0)]

In [41]:
%%sql

-- For each product that has more than three items sold within all sales transactions, retrieve the productID value and the total number of product items sold within all sales transaction.

SELECT productid, SUM(noofitems) as total_items
FROM soldvia
GROUP BY productid
HAVING SUM(noofitems) > 3;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X2', 8),
 ('1X4', 7),
 ('2X1', 6),
 ('2X2', 13),
 ('2X3', 5),
 ('2X4', 12),
 ('3X1', 6),
 ('3X3', 12),
 ('3X4', 6),
 ('4X2', 4),
 ('4X3', 4),
 ('4X4', 7),
 ('8X8', 4),
 ('9X9', 5)]

In [42]:
%%sql


-- For each product that was sold in more than one sales transaction, retrieve the ProductID value and the number of sales transactions in which the product was sold.

SELECT productid, COUNT(tid) as num_transactions
FROM soldvia
GROUP BY productid
HAVING COUNT(tid) > 1;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 2),
 ('1X2', 2),
 ('1X3', 2),
 ('1X4', 3),
 ('2X1', 2),
 ('2X2', 6),
 ('2X3', 2),
 ('2X4', 3),
 ('3X1', 2),
 ('3X2', 2),
 ('3X3', 3),
 ('3X4', 2),
 ('4X2', 2),
 ('4X3', 2),
 ('4X4', 3),
 ('6X6', 2),
 ('8X8', 2),
 ('9X9', 3)]

In [43]:
%%sql

-- For each product that has more than three items sold within all sales transactions, retrieve the ProductID value.

SElECT *
FROM soldvia;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'T111', 1),
 ('2X2', 'T222', 1),
 ('3X3', 'T333', 5),
 ('1X1', 'T333', 1),
 ('4X4', 'T444', 1),
 ('2X2', 'T444', 2),
 ('4X4', 'T555', 4),
 ('5X5', 'T555', 2),
 ('6X6', 'T555', 1),
 ('7X7', 'T666', 1),
 ('9X9', 'T666', 1),
 ('1X3', 'T666', 2),
 ('8X8', 'T777', 1),
 ('1X4', 'T888', 4),
 ('2X3', 'T888', 3),
 ('9X9', 'T999', 1),
 ('1X2', 'T999', 5),
 ('8X8', 'T999', 3),
 ('1X3', 'T999', 1),
 ('1X2', 'T101', 3),
 ('1X4', 'T101', 1),
 ('2X4', 'T202', 4),
 ('9X9', 'T303', 3),
 ('1X4', 'T303', 2),
 ('2X1', 'T303', 2),
 ('3X1', 'T303', 2),
 ('2X4', 'T404', 1),
 ('2X3', 'T404', 2),
 ('2X2', 'T505', 3),
 ('3X2', 'T505', 1),
 ('2X1', 'T505', 4),
 ('2X4', 'T606', 7),
 ('3X1', 'T606', 4),
 ('2X2', 'T606', 3),
 ('3X4', 'T606', 2),
 ('4X4', 'T606', 2),
 ('3X2', 'T707', 1),
 ('3X4', 'T707', 4),
 ('4X1', 'T707', 2),
 ('5X3', 'T808', 1),
 ('4X2', 'T808', 1),
 ('2X2', 'T808', 1),
 ('4X3', 'T808', 1),
 ('3X3', 'T808', 4),
 ('4X2', 'T909', 3),
 ('6X6', 'T909', 1),
 ('3X3', 'T011', 3),
 ('4X3', 'T022', 3),
 ('2X2', 'T022', 3),
 ('5X1', 'T022', 2)]

In [44]:
%%sql

-- For each product that has more than three items sold within all sales transactions, retrieve the ProductID value.

SElECT productid
FROM soldvia
GROUP BY productid
HAVING SUM(noofitems) > 3;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X2',),
 ('1X4',),
 ('2X1',),
 ('2X2',),
 ('2X3',),
 ('2X4',),
 ('3X1',),
 ('3X3',),
 ('3X4',),
 ('4X2',),
 ('4X3',),
 ('4X4',),
 ('8X8',),
 ('9X9',)]

## *Nested Queries*

*   A nested query is also referred to as an inner query
*   The query that uses the nested query is referred to as an outer query

In [45]:
%%sql

-- Retrieve product id, product name, and product price for those product whose product price is lower than the average price

SELECT productid, productname, productprice
FROM product
WHERE productprice < (SELECT AVG(productprice) FROM product);

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100),
 ('2X2', 'Easy Boot', 70),
 ('3X3', 'Cosy Sock', 15),
 ('4X4', 'Dura Boot', 90),
 ('8X8', 'Power Pedals', 20),
 ('9X9', 'Trusty Rope', 30),
 ('1X4', 'Safe-T Helmet', 40),
 ('2X1', 'Mmm Stove', 80),
 ('2X3', 'Reflect-o Jacket', 35),
 ('2X4', 'Strongster Carribeaner', 20),
 ('3X1', 'Sleepy Pad', 25),
 ('3X2', 'Bucky Knife', 60),
 ('3X4', 'Treado Tire', 30),
 ('4X1', 'Slicky Tire', 25),
 ('4X2', 'Electra Compass', 45),
 ('5X1', 'Simple Sandal', 50),
 ('5X2', 'Action Sandal', 70)]

In [46]:
%%sql

SELECT AVG(productprice) FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[(106.45833333333333,)]

## **IN**

An alternative, checking if element is in a list.

In [47]:
%%sql

-- Retrieve the product id, product name, and produce price for products whose product id is either 1x1 1or 2x2 or 3x3

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[]

In [48]:
%%sql

SELECT productid, productname, productprice
FROM product
WHERE productid = '1X1' OR productid = '2X2' OR productid = '3X3';

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100), ('2X2', 'Easy Boot', 70), ('3X3', 'Cosy Sock', 15)]

In [49]:
%%sql

-- Alternative to where and multiple conditions
SELECT productid, productname, productprice
FROM product
WHERE productid IN ('1X1', '2X2', '3X3');

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100), ('2X2', 'Easy Boot', 70), ('3X3', 'Cosy Sock', 15)]

In [50]:
%%sql

-- For each product whose items where sold in more than one sales transaction, retrieve the product id, product name, and product price

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[]

# **Alias**

In [51]:
%%sql

SELECT productname as ProductName
FROM product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('Zzz Bag',),
 ('Easy Boot',),
 ('Cosy Sock',),
 ('Dura Boot',),
 ('Tiny Tent',),
 ('Biggy Tent',),
 ('Hi-Tec GPS',),
 ('Power Pedals',),
 ('Trusty Rope',),
 ('Comfy Harness',),
 ('Sunny Charger',),
 ('Safe-T Helmet',),
 ('Mmm Stove',),
 ('Reflect-o Jacket',),
 ('Strongster Carribeaner',),
 ('Sleepy Pad',),
 ('Bucky Knife',),
 ('Treado Tire',),
 ('Slicky Tire',),
 ('Electra Compass',),
 ('Mega Camera',),
 ('Simple Sandal',),
 ('Action Sandal',),
 ('Luxo Tent',)]

# **Putting information together from multiple tables**

## **JOIN (INNER JOIN)**

What happens when we want to merge information from multiple tables? That's when we `JOIN`

In the next couple of cells I will give you an example of a BAD way of putting things together. That will emphasize the importance of using `JOIN`

In [52]:
%%sql

-- THIS IS BAD and BANNED :)
-- Just to give you an idea of what you should not do
-- How do we want to put things together?

SELECT *
FROM product, vendor;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100, 'PG', 'CP', 'PG', 'Pacifica Gear'),
 ('1X1', 'Zzz Bag', 100, 'PG', 'CP', 'MK', 'Mountain King'),
 ('1X1', 'Zzz Bag', 100, 'PG', 'CP', 'OA', 'Outdoor Adventures'),
 ('1X1', 'Zzz Bag', 100, 'PG', 'CP', 'WL', 'Wilderness Limited'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW', 'PG', 'Pacifica Gear'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW', 'MK', 'Mountain King'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW', 'OA', 'Outdoor Adventures'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW', 'WL', 'Wilderness Limited'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW', 'PG', 'Pacifica Gear'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW', 'MK', 'Mountain King'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW', 'OA', 'Outdoor Adventures'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW', 'WL', 'Wilderness Limited'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW', 'MK', 'Mountain King'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW', 'OA', 'Outdoor Adventures'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW', 'WL', 'Wilderness Limited'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP', 'PG', 'Pacifica Gear'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP', 'MK', 'Mountain King'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP', 'OA', 'Outdoor Adventures'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP', 'WL', 'Wilderness Limited'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP', 'PG', 'Pacifica Gear'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP', 'MK', 'Mountain King'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP', 'OA', 'Outdoor Adventures'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP', 'WL', 'Wilderness Limited'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL', 'PG', 'Pacifica Gear'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL', 'MK', 'Mountain King'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL', 'OA', 'Outdoor Adventures'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL', 'WL', 'Wilderness Limited'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY', 'PG', 'Pacifica Gear'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY', 'MK', 'Mountain King'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY', 'OA', 'Outdoor Adventures'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY', 'WL', 'Wilderness Limited'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL', 'PG', 'Pacifica Gear'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL', 'MK', 'Mountain King'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL', 'OA', 'Outdoor Adventures'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL', 'WL', 'Wilderness Limited'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL', 'PG', 'Pacifica Gear'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL', 'MK', 'Mountain King'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL', 'OA', 'Outdoor Adventures'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL', 'WL', 'Wilderness Limited'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL', 'PG', 'Pacifica Gear'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL', 'MK', 'Mountain King'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL', 'OA', 'Outdoor Adventures'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL', 'WL', 'Wilderness Limited'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY', 'PG', 'Pacifica Gear'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY', 'MK', 'Mountain King'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY', 'OA', 'Outdoor Adventures'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY', 'WL', 'Wilderness Limited'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP', 'PG', 'Pacifica Gear'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP', 'MK', 'Mountain King'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP', 'OA', 'Outdoor Adventures'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY', 'PG', 'Pacifica Gear'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY', 'MK', 'Mountain King'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY', 'OA', 'Outdoor Adventures'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY', 'WL', 'Wilderness Limited'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL', 'PG', 'Pacifica Gear'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL', 'MK', 'Mountain King'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL', 'OA', 'Outdoor Adventures'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL', 'WL', 'Wilderness Limited'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP', 'PG', 'Pacifica Gear'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP', 'MK', 'Mountain King'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP', 'OA', 'Outdoor Adventures'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP', 'PG', 'Pacifica Gear'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP', 'MK', 'Mountain King'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP', 'OA', 'Outdoor Adventures'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY', 'PG', 'Pacifica Gear'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY', 'MK', 'Mountain King'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY', 'OA', 'Outdoor Adventures'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY', 'WL', 'Wilderness Limited'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY', 'PG', 'Pacifica Gear'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY', 'MK', 'Mountain King'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY', 'OA', 'Outdoor Adventures'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY', 'WL', 'Wilderness Limited'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL', 'PG', 'Pacifica Gear'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL', 'MK', 'Mountain King'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL', 'OA', 'Outdoor Adventures'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL', 'WL', 'Wilderness Limited'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL', 'PG', 'Pacifica Gear'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL', 'MK', 'Mountain King'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL', 'OA', 'Outdoor Adventures'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL', 'WL', 'Wilderness Limited'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW', 'MK', 'Mountain King'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW', 'OA', 'Outdoor Adventures'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW', 'WL', 'Wilderness Limited'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW', 'MK', 'Mountain King'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW', 'OA', 'Outdoor Adventures'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW', 'WL', 'Wilderness Limited'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP', 'PG', 'Pacifica Gear'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP', 'MK', 'Mountain King'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP', 'OA', 'Outdoor Adventures'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP', 'WL', 'Wilderness Limited')]

In [53]:
%%sql

-- For each product, we show all available information about the product AND the vendor

SELECT *
FROM product p, vendor v
WHERE p.vendorid = v.vendorid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100, 'PG', 'CP', 'PG', 'Pacifica Gear'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW', 'MK', 'Mountain King'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW', 'MK', 'Mountain King'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP', 'MK', 'Mountain King'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP', 'MK', 'Mountain King'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL', 'OA', 'Outdoor Adventures'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY', 'MK', 'Mountain King'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL', 'WL', 'Wilderness Limited'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL', 'MK', 'Mountain King'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL', 'OA', 'Outdoor Adventures'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY', 'PG', 'Pacifica Gear'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY', 'PG', 'Pacifica Gear'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL', 'MK', 'Mountain King'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY', 'OA', 'Outdoor Adventures'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY', 'OA', 'Outdoor Adventures'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL', 'MK', 'Mountain King'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL', 'WL', 'Wilderness Limited'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP', 'OA', 'Outdoor Adventures')]

In [54]:
%%sql

-- For each product, we show all available information about the product AND the vendor

SELECT product.productid, product.productname, product.categoryid, product.productprice, vendor.vendorid, vendor.vendorname
FROM product, vendor
WHERE product.vendorid = vendor.vendorid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 'CP', 100, 'PG', 'Pacifica Gear'),
 ('2X2', 'Easy Boot', 'FW', 70, 'MK', 'Mountain King'),
 ('3X3', 'Cosy Sock', 'FW', 15, 'MK', 'Mountain King'),
 ('4X4', 'Dura Boot', 'FW', 90, 'PG', 'Pacifica Gear'),
 ('5X5', 'Tiny Tent', 'CP', 150, 'MK', 'Mountain King'),
 ('6X6', 'Biggy Tent', 'CP', 250, 'MK', 'Mountain King'),
 ('7X7', 'Hi-Tec GPS', 'EL', 300, 'OA', 'Outdoor Adventures'),
 ('8X8', 'Power Pedals', 'CY', 20, 'MK', 'Mountain King'),
 ('9X9', 'Trusty Rope', 'CL', 30, 'WL', 'Wilderness Limited'),
 ('1X2', 'Comfy Harness', 'CL', 150, 'MK', 'Mountain King'),
 ('1X3', 'Sunny Charger', 'EL', 125, 'OA', 'Outdoor Adventures'),
 ('1X4', 'Safe-T Helmet', 'CY', 40, 'PG', 'Pacifica Gear'),
 ('2X1', 'Mmm Stove', 'CP', 80, 'WL', 'Wilderness Limited'),
 ('2X3', 'Reflect-o Jacket', 'CY', 35, 'PG', 'Pacifica Gear'),
 ('2X4', 'Strongster Carribeaner', 'CL', 20, 'MK', 'Mountain King'),
 ('3X1', 'Sleepy Pad', 'CP', 25, 'WL', 'Wilderness Limited'),
 ('3X2', 'Bucky Knife', 'CP', 60, 'WL', 'Wilderness Limited'),
 ('3X4', 'Treado Tire', 'CY', 30, 'OA', 'Outdoor Adventures'),
 ('4X1', 'Slicky Tire', 'CY', 25, 'OA', 'Outdoor Adventures'),
 ('4X2', 'Electra Compass', 'EL', 45, 'MK', 'Mountain King'),
 ('4X3', 'Mega Camera', 'EL', 275, 'WL', 'Wilderness Limited'),
 ('5X1', 'Simple Sandal', 'FW', 50, 'PG', 'Pacifica Gear'),
 ('5X2', 'Action Sandal', 'FW', 70, 'PG', 'Pacifica Gear'),
 ('5X3', 'Luxo Tent', 'CP', 500, 'OA', 'Outdoor Adventures')]

In [55]:
%%sql

-- Write with the join: For each product, we show all available information about the product AND the vendor
SELECT *
FROM product p
JOIN vendor v
ON p.vendorid = v.vendorid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100, 'PG', 'CP', 'PG', 'Pacifica Gear'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW', 'MK', 'Mountain King'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW', 'MK', 'Mountain King'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP', 'MK', 'Mountain King'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP', 'MK', 'Mountain King'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL', 'OA', 'Outdoor Adventures'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY', 'MK', 'Mountain King'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL', 'WL', 'Wilderness Limited'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL', 'MK', 'Mountain King'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL', 'OA', 'Outdoor Adventures'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY', 'PG', 'Pacifica Gear'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY', 'PG', 'Pacifica Gear'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL', 'MK', 'Mountain King'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP', 'WL', 'Wilderness Limited'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY', 'OA', 'Outdoor Adventures'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY', 'OA', 'Outdoor Adventures'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL', 'MK', 'Mountain King'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL', 'WL', 'Wilderness Limited'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW', 'PG', 'Pacifica Gear'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP', 'OA', 'Outdoor Adventures')]

In [56]:
%%sql

-- For each product, retrieve the product ID, name of the product, name of the vendor for the product, and price of the product

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[]

In [57]:
%%sql

-- Write with the join: For each product, retrieve the product ID, name of the product, name of the vendor for the product, and price of the product

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[]

In [58]:
%%sql
SELECT *
from product;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'Zzz Bag', 100, 'PG', 'CP'),
 ('2X2', 'Easy Boot', 70, 'MK', 'FW'),
 ('3X3', 'Cosy Sock', 15, 'MK', 'FW'),
 ('4X4', 'Dura Boot', 90, 'PG', 'FW'),
 ('5X5', 'Tiny Tent', 150, 'MK', 'CP'),
 ('6X6', 'Biggy Tent', 250, 'MK', 'CP'),
 ('7X7', 'Hi-Tec GPS', 300, 'OA', 'EL'),
 ('8X8', 'Power Pedals', 20, 'MK', 'CY'),
 ('9X9', 'Trusty Rope', 30, 'WL', 'CL'),
 ('1X2', 'Comfy Harness', 150, 'MK', 'CL'),
 ('1X3', 'Sunny Charger', 125, 'OA', 'EL'),
 ('1X4', 'Safe-T Helmet', 40, 'PG', 'CY'),
 ('2X1', 'Mmm Stove', 80, 'WL', 'CP'),
 ('2X3', 'Reflect-o Jacket', 35, 'PG', 'CY'),
 ('2X4', 'Strongster Carribeaner', 20, 'MK', 'CL'),
 ('3X1', 'Sleepy Pad', 25, 'WL', 'CP'),
 ('3X2', 'Bucky Knife', 60, 'WL', 'CP'),
 ('3X4', 'Treado Tire', 30, 'OA', 'CY'),
 ('4X1', 'Slicky Tire', 25, 'OA', 'CY'),
 ('4X2', 'Electra Compass', 45, 'MK', 'EL'),
 ('4X3', 'Mega Camera', 275, 'WL', 'EL'),
 ('5X1', 'Simple Sandal', 50, 'PG', 'FW'),
 ('5X2', 'Action Sandal', 70, 'PG', 'FW'),
 ('5X3', 'Luxo Tent', 500, 'OA', 'CP')]

In [59]:
%%sql
SELECT *
FROM salestransaction;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('T111', '1-2-333', 'S1', '2013-01-01'),
 ('T222', '2-3-444', 'S2', '2013-01-01'),
 ('T333', '1-2-333', 'S3', '2013-01-02'),
 ('T444', '3-4-555', 'S3', '2013-01-02'),
 ('T555', '2-3-444', 'S3', '2013-01-02'),
 ('T666', '5-6-777', 'S10', '2013-01-03'),
 ('T777', '6-7-888', 'S13', '2013-01-03'),
 ('T888', '8-9-000', 'S4', '2013-01-04'),
 ('T999', '4-5-666', 'S6', '2013-01-04'),
 ('T101', '7-8-999', 'S12', '2013-01-04'),
 ('T202', '0-1-222', 'S8', '2013-01-04'),
 ('T303', '4-5-666', 'S6', '2013-01-05'),
 ('T404', '8-9-000', 'S6', '2013-01-05'),
 ('T505', '6-7-888', 'S14', '2013-01-05'),
 ('T606', '0-1-222', 'S11', '2013-01-06'),
 ('T707', '5-6-777', 'S4', '2013-01-06'),
 ('T808', '7-8-999', 'S9', '2013-01-06'),
 ('T909', '5-6-777', 'S4', '2013-01-06'),
 ('T011', '8-9-000', 'S7', '2013-01-07'),
 ('T022', '9-0-111', 'S5', '2013-01-07')]

In [60]:
%%sql
SELECT *
FROM soldvia;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('1X1', 'T111', 1),
 ('2X2', 'T222', 1),
 ('3X3', 'T333', 5),
 ('1X1', 'T333', 1),
 ('4X4', 'T444', 1),
 ('2X2', 'T444', 2),
 ('4X4', 'T555', 4),
 ('5X5', 'T555', 2),
 ('6X6', 'T555', 1),
 ('7X7', 'T666', 1),
 ('9X9', 'T666', 1),
 ('1X3', 'T666', 2),
 ('8X8', 'T777', 1),
 ('1X4', 'T888', 4),
 ('2X3', 'T888', 3),
 ('9X9', 'T999', 1),
 ('1X2', 'T999', 5),
 ('8X8', 'T999', 3),
 ('1X3', 'T999', 1),
 ('1X2', 'T101', 3),
 ('1X4', 'T101', 1),
 ('2X4', 'T202', 4),
 ('9X9', 'T303', 3),
 ('1X4', 'T303', 2),
 ('2X1', 'T303', 2),
 ('3X1', 'T303', 2),
 ('2X4', 'T404', 1),
 ('2X3', 'T404', 2),
 ('2X2', 'T505', 3),
 ('3X2', 'T505', 1),
 ('2X1', 'T505', 4),
 ('2X4', 'T606', 7),
 ('3X1', 'T606', 4),
 ('2X2', 'T606', 3),
 ('3X4', 'T606', 2),
 ('4X4', 'T606', 2),
 ('3X2', 'T707', 1),
 ('3X4', 'T707', 4),
 ('4X1', 'T707', 2),
 ('5X3', 'T808', 1),
 ('4X2', 'T808', 1),
 ('2X2', 'T808', 1),
 ('4X3', 'T808', 1),
 ('3X3', 'T808', 4),
 ('4X2', 'T909', 3),
 ('6X6', 'T909', 1),
 ('3X3', 'T011', 3),
 ('4X3', 'T022', 3),
 ('2X2', 'T022', 3),
 ('5X1', 'T022', 2)]

In [61]:
%%sql

-- For each line item of a sales transaction, retrieve the transaction id, date of the transaction, product name, quantity sold, and amount charged; ordered by transaction id

SELECT t.tid, t.tdate, p.productname, p.productid, s.noofitems, s.noofitems * p.productprice
FROM salestransaction t, soldvia s, product p
WHERE t.tid = s.tid AND s.productid = p.productid
ORDER BY t.tid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('T011', '2013-01-07', 'Cosy Sock', '3X3', 3, 45),
 ('T022', '2013-01-07', 'Mega Camera', '4X3', 3, 825),
 ('T022', '2013-01-07', 'Easy Boot', '2X2', 3, 210),
 ('T022', '2013-01-07', 'Simple Sandal', '5X1', 2, 100),
 ('T101', '2013-01-04', 'Comfy Harness', '1X2', 3, 450),
 ('T101', '2013-01-04', 'Safe-T Helmet', '1X4', 1, 40),
 ('T111', '2013-01-01', 'Zzz Bag', '1X1', 1, 100),
 ('T202', '2013-01-04', 'Strongster Carribeaner', '2X4', 4, 80),
 ('T222', '2013-01-01', 'Easy Boot', '2X2', 1, 70),
 ('T303', '2013-01-05', 'Trusty Rope', '9X9', 3, 90),
 ('T303', '2013-01-05', 'Safe-T Helmet', '1X4', 2, 80),
 ('T303', '2013-01-05', 'Mmm Stove', '2X1', 2, 160),
 ('T303', '2013-01-05', 'Sleepy Pad', '3X1', 2, 50),
 ('T333', '2013-01-02', 'Cosy Sock', '3X3', 5, 75),
 ('T333', '2013-01-02', 'Zzz Bag', '1X1', 1, 100),
 ('T404', '2013-01-05', 'Strongster Carribeaner', '2X4', 1, 20),
 ('T404', '2013-01-05', 'Reflect-o Jacket', '2X3', 2, 70),
 ('T444', '2013-01-02', 'Dura Boot', '4X4', 1, 90),
 ('T444', '2013-01-02', 'Easy Boot', '2X2', 2, 140),
 ('T505', '2013-01-05', 'Easy Boot', '2X2', 3, 210),
 ('T505', '2013-01-05', 'Bucky Knife', '3X2', 1, 60),
 ('T505', '2013-01-05', 'Mmm Stove', '2X1', 4, 320),
 ('T555', '2013-01-02', 'Dura Boot', '4X4', 4, 360),
 ('T555', '2013-01-02', 'Tiny Tent', '5X5', 2, 300),
 ('T555', '2013-01-02', 'Biggy Tent', '6X6', 1, 250),
 ('T606', '2013-01-06', 'Strongster Carribeaner', '2X4', 7, 140),
 ('T606', '2013-01-06', 'Sleepy Pad', '3X1', 4, 100),
 ('T606', '2013-01-06', 'Easy Boot', '2X2', 3, 210),
 ('T606', '2013-01-06', 'Treado Tire', '3X4', 2, 60),
 ('T606', '2013-01-06', 'Dura Boot', '4X4', 2, 180),
 ('T666', '2013-01-03', 'Hi-Tec GPS', '7X7', 1, 300),
 ('T666', '2013-01-03', 'Trusty Rope', '9X9', 1, 30),
 ('T666', '2013-01-03', 'Sunny Charger', '1X3', 2, 250),
 ('T707', '2013-01-06', 'Bucky Knife', '3X2', 1, 60),
 ('T707', '2013-01-06', 'Treado Tire', '3X4', 4, 120),
 ('T707', '2013-01-06', 'Slicky Tire', '4X1', 2, 50),
 ('T777', '2013-01-03', 'Power Pedals', '8X8', 1, 20),
 ('T808', '2013-01-06', 'Luxo Tent', '5X3', 1, 500),
 ('T808', '2013-01-06', 'Electra Compass', '4X2', 1, 45),
 ('T808', '2013-01-06', 'Easy Boot', '2X2', 1, 70),
 ('T808', '2013-01-06', 'Mega Camera', '4X3', 1, 275),
 ('T808', '2013-01-06', 'Cosy Sock', '3X3', 4, 60),
 ('T888', '2013-01-04', 'Safe-T Helmet', '1X4', 4, 160),
 ('T888', '2013-01-04', 'Reflect-o Jacket', '2X3', 3, 105),
 ('T909', '2013-01-06', 'Electra Compass', '4X2', 3, 135),
 ('T909', '2013-01-06', 'Biggy Tent', '6X6', 1, 250),
 ('T999', '2013-01-04', 'Trusty Rope', '9X9', 1, 30),
 ('T999', '2013-01-04', 'Comfy Harness', '1X2', 5, 750),
 ('T999', '2013-01-04', 'Power Pedals', '8X8', 3, 60),
 ('T999', '2013-01-04', 'Sunny Charger', '1X3', 1, 125)]

In [62]:
%%sql

-- For each line item of a sales transaction, retrieve the transaction id, date of the transaction, product name, quantity sold, and amount charged; ordered by transaction id

SELECT t.tid, t.tdate, p.productname, p.productid, s.noofitems, s.noofitems * p.productprice
FROM salestransaction t
JOIN soldvia s
ON t.tid = s.tid
JOIN product p
ON s.productid = p.productid
ORDER BY t.tid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('T011', '2013-01-07', 'Cosy Sock', '3X3', 3, 45),
 ('T022', '2013-01-07', 'Mega Camera', '4X3', 3, 825),
 ('T022', '2013-01-07', 'Easy Boot', '2X2', 3, 210),
 ('T022', '2013-01-07', 'Simple Sandal', '5X1', 2, 100),
 ('T101', '2013-01-04', 'Comfy Harness', '1X2', 3, 450),
 ('T101', '2013-01-04', 'Safe-T Helmet', '1X4', 1, 40),
 ('T111', '2013-01-01', 'Zzz Bag', '1X1', 1, 100),
 ('T202', '2013-01-04', 'Strongster Carribeaner', '2X4', 4, 80),
 ('T222', '2013-01-01', 'Easy Boot', '2X2', 1, 70),
 ('T303', '2013-01-05', 'Trusty Rope', '9X9', 3, 90),
 ('T303', '2013-01-05', 'Safe-T Helmet', '1X4', 2, 80),
 ('T303', '2013-01-05', 'Mmm Stove', '2X1', 2, 160),
 ('T303', '2013-01-05', 'Sleepy Pad', '3X1', 2, 50),
 ('T333', '2013-01-02', 'Cosy Sock', '3X3', 5, 75),
 ('T333', '2013-01-02', 'Zzz Bag', '1X1', 1, 100),
 ('T404', '2013-01-05', 'Strongster Carribeaner', '2X4', 1, 20),
 ('T404', '2013-01-05', 'Reflect-o Jacket', '2X3', 2, 70),
 ('T444', '2013-01-02', 'Dura Boot', '4X4', 1, 90),
 ('T444', '2013-01-02', 'Easy Boot', '2X2', 2, 140),
 ('T505', '2013-01-05', 'Easy Boot', '2X2', 3, 210),
 ('T505', '2013-01-05', 'Bucky Knife', '3X2', 1, 60),
 ('T505', '2013-01-05', 'Mmm Stove', '2X1', 4, 320),
 ('T555', '2013-01-02', 'Dura Boot', '4X4', 4, 360),
 ('T555', '2013-01-02', 'Tiny Tent', '5X5', 2, 300),
 ('T555', '2013-01-02', 'Biggy Tent', '6X6', 1, 250),
 ('T606', '2013-01-06', 'Strongster Carribeaner', '2X4', 7, 140),
 ('T606', '2013-01-06', 'Sleepy Pad', '3X1', 4, 100),
 ('T606', '2013-01-06', 'Easy Boot', '2X2', 3, 210),
 ('T606', '2013-01-06', 'Treado Tire', '3X4', 2, 60),
 ('T606', '2013-01-06', 'Dura Boot', '4X4', 2, 180),
 ('T666', '2013-01-03', 'Hi-Tec GPS', '7X7', 1, 300),
 ('T666', '2013-01-03', 'Trusty Rope', '9X9', 1, 30),
 ('T666', '2013-01-03', 'Sunny Charger', '1X3', 2, 250),
 ('T707', '2013-01-06', 'Bucky Knife', '3X2', 1, 60),
 ('T707', '2013-01-06', 'Treado Tire', '3X4', 4, 120),
 ('T707', '2013-01-06', 'Slicky Tire', '4X1', 2, 50),
 ('T777', '2013-01-03', 'Power Pedals', '8X8', 1, 20),
 ('T808', '2013-01-06', 'Luxo Tent', '5X3', 1, 500),
 ('T808', '2013-01-06', 'Electra Compass', '4X2', 1, 45),
 ('T808', '2013-01-06', 'Easy Boot', '2X2', 1, 70),
 ('T808', '2013-01-06', 'Mega Camera', '4X3', 1, 275),
 ('T808', '2013-01-06', 'Cosy Sock', '3X3', 4, 60),
 ('T888', '2013-01-04', 'Safe-T Helmet', '1X4', 4, 160),
 ('T888', '2013-01-04', 'Reflect-o Jacket', '2X3', 3, 105),
 ('T909', '2013-01-06', 'Electra Compass', '4X2', 3, 135),
 ('T909', '2013-01-06', 'Biggy Tent', '6X6', 1, 250),
 ('T999', '2013-01-04', 'Trusty Rope', '9X9', 1, 30),
 ('T999', '2013-01-04', 'Comfy Harness', '1X2', 5, 750),
 ('T999', '2013-01-04', 'Power Pedals', '8X8', 3, 60),
 ('T999', '2013-01-04', 'Sunny Charger', '1X3', 1, 125)]

## **OUTER JOIN**

An OUTER JOIN returns all rows from one table and the matched rows from the other table. If there is no match, NULL values are returned for the columns of the non-matching table. There are different types of OUTER JOINs: LEFT (OUTER) JOIN, RIGHT (OUTER) JOIN, and FULL (OUTER) JOIN.

Here's an example of a LEFT (OUTER) JOIN.

In [63]:
%%sql

-- LEFT JOIN example: Get all vendors and the products they supply.
-- If a vendor doesn't supply any products, the product columns will be NULL.
SELECT *
FROM vendor v
LEFT JOIN product p
ON v.vendorid = p.vendorid;

 * sqlite:////Users/vanessadamario/src/DataManagement-BusinessIntelligence/zagimore.db
Done.

[('PG', 'Pacifica Gear', '1X1', 'Zzz Bag', 100, 'PG', 'CP'),
 ('PG', 'Pacifica Gear', '1X4', 'Safe-T Helmet', 40, 'PG', 'CY'),
 ('PG', 'Pacifica Gear', '2X3', 'Reflect-o Jacket', 35, 'PG', 'CY'),
 ('PG', 'Pacifica Gear', '4X4', 'Dura Boot', 90, 'PG', 'FW'),
 ('PG', 'Pacifica Gear', '5X1', 'Simple Sandal', 50, 'PG', 'FW'),
 ('PG', 'Pacifica Gear', '5X2', 'Action Sandal', 70, 'PG', 'FW'),
 ('MK', 'Mountain King', '1X2', 'Comfy Harness', 150, 'MK', 'CL'),
 ('MK', 'Mountain King', '2X2', 'Easy Boot', 70, 'MK', 'FW'),
 ('MK', 'Mountain King', '2X4', 'Strongster Carribeaner', 20, 'MK', 'CL'),
 ('MK', 'Mountain King', '3X3', 'Cosy Sock', 15, 'MK', 'FW'),
 ('MK', 'Mountain King', '4X2', 'Electra Compass', 45, 'MK', 'EL'),
 ('MK', 'Mountain King', '5X5', 'Tiny Tent', 150, 'MK', 'CP'),
 ('MK', 'Mountain King', '6X6', 'Biggy Tent', 250, 'MK', 'CP'),
 ('MK', 'Mountain King', '8X8', 'Power Pedals', 20, 'MK', 'CY'),
 ('OA', 'Outdoor Adventures', '1X3', 'Sunny Charger', 125, 'OA', 'EL'),
 ('OA', 'Outdoor Adventures', '3X4', 'Treado Tire', 30, 'OA', 'CY'),
 ('OA', 'Outdoor Adventures', '4X1', 'Slicky Tire', 25, 'OA', 'CY'),
 ('OA', 'Outdoor Adventures', '5X3', 'Luxo Tent', 500, 'OA', 'CP'),
 ('OA', 'Outdoor Adventures', '7X7', 'Hi-Tec GPS', 300, 'OA', 'EL'),
 ('WL', 'Wilderness Limited', '2X1', 'Mmm Stove', 80, 'WL', 'CP'),
 ('WL', 'Wilderness Limited', '3X1', 'Sleepy Pad', 25, 'WL', 'CP'),
 ('WL', 'Wilderness Limited', '3X2', 'Bucky Knife', 60, 'WL', 'CP'),
 ('WL', 'Wilderness Limited', '4X3', 'Mega Camera', 275, 'WL', 'EL'),
 ('WL', 'Wilderness Limited', '9X9', 'Trusty Rope', 30, 'WL', 'CL')]

RIGHT JOIN

A RIGHT JOIN returns all rows from the right table (the second table in the `FROM` clause) and the matched rows from the left table. If there is no match in the left table, the columns from the left table will have `NULL` values.

*Note: SQLite does not directly support RIGHT JOIN. A common way to achieve the same result in SQLite is to use a LEFT JOIN and reverse the order of the tables.*

Here's how you can achieve the equivalent of a RIGHT JOIN in SQLite, showing all products and their vendors. If a product has no matching vendor (though this shouldn't happen with this schema's foreign keys, it illustrates the concept), the vendor columns would be NULL.

FULL JOIN

A FULL JOIN returns all rows when there is a match in either the left or the right table. If there are rows in one table that do not have matches in the other, those rows will also be included, and the columns from the non-matching table will have `NULL` values.

*Note: SQLite does not directly support FULL JOIN. A common way to achieve the same result in SQLite is to combine a LEFT JOIN and a RIGHT JOIN (simulated with LEFT JOIN by swapping tables) using `UNION` and filtering out duplicates.*

Here's how you can achieve the equivalent of a FULL JOIN in SQLite, showing all vendors and all products, regardless of whether they have a match in the other table.